# Generated by Django 6.0.4 on 2026-04-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('arquivo', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('delimitador', models.CharField(default='auto', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('error', 'Erro')], default='pending', max_length=20)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('total_colunas', models.PositiveIntegerField(default=0)),
                ('colunas', models.JSONField(blank=True, default=list)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'ordering': ['-criado_em'],
            },
        ),
    ]
