# Generated by Django 5.2.13 on 2026-04-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingrun',
            name='delimitador',
        ),
        migrations.AddField(
            model_name='processingrun',
            name='origem',
            field=models.CharField(default='server', max_length=50),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='parametros_busca',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='processingrun',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
